### ISSUE TITLE
限制说明

### ISSUE THREAD

**Issue by zhugelianglongming** [limeng120/xchaintest#6]
测试脚本对于 xuperchain/xupercore 的部署节点数量、端口、路径等，有没有限制要求？相应的限制要求是什么？

优化思路：
- 通过 README 等文档说明，让使用者遵守约定
- 通过代码自动获取其中的部分参数

**Comment by limeng120** [comment]
readme中说明了需部署3节点的网络
端口、路径不限制，用户部署的环境用什么端口，就在xchaintest配置文件改为什么端口。readme有配置说明

**Comment by limeng120** [comment]
> 测试脚本对于 xuperchain/xupercore 的部署节点数量、端口、路径等，有没有限制要求？相应的限制要求是什么？
> 
> 优化思路：
> 
> * 通过 README 等文档说明，让使用者遵守约定
> * 通过代码自动获取其中的部分参数

readme中说明了需部署3节点的网络
端口、路径不限制，用户部署的环境用什么端口，就在xchaintest配置文件改为什么端口。readme有配置说明

**Comment by limeng120** [comment]
xuperchain默认部署的3个节点，端口是37101 37102 37103  所以xchaintest默认也是这三个端口
